In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv(r"D:\Datasets\house-prices-advanced-regression-techniques\train.csv")
data


Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [3]:
data.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

Removing null values

In [4]:

col = "LotFrontage"
for i in col:
    data[col] = data[col].fillna(data[col].mean())
data[col]


0       65.0
1       80.0
2       68.0
3       60.0
4       84.0
        ... 
1455    62.0
1456    85.0
1457    66.0
1458    68.0
1459    75.0
Name: LotFrontage, Length: 1460, dtype: float64

In [5]:
data.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 81, dtype: int64

Replacing Nan values as 0

In [6]:
col = 'Alley','PoolQC','Fence','MiscFeature'
for i in col:
    data[i] = data[i].replace(np.nan,0)
data[i]

0          0
1          0
2          0
3          0
4          0
        ... 
1455       0
1456       0
1457    Shed
1458       0
1459       0
Name: MiscFeature, Length: 1460, dtype: object

In [7]:
data

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave     0      Reg   
1        2          20       RL         80.0     9600   Pave     0      Reg   
2        3          60       RL         68.0    11250   Pave     0      IR1   
3        4          70       RL         60.0     9550   Pave     0      IR1   
4        5          60       RL         84.0    14260   Pave     0      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave     0      Reg   
1456  1457          20       RL         85.0    13175   Pave     0      Reg   
1457  1458          70       RL         66.0     9042   Pave     0      Reg   
1458  1459          20       RL         68.0     9717   Pave     0      Reg   
1459  1460          20       RL         75.0     9937   Pave     0      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0      0      0           0       0   
1            Lvl    AllPub  ...        0      0      0           0       0   
2            Lvl    AllPub  ...        0      0      0           0       0   
3            Lvl    AllPub  ...        0      0      0           0       0   
4            Lvl    AllPub  ...        0      0      0           0       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0      0      0           0       0   
1456         Lvl    AllPub  ...        0      0  MnPrv           0       0   
1457         Lvl    AllPub  ...        0      0  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0      0      0           0       0   
1459         Lvl    AllPub  ...        0      0      0           0       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [8]:
x = data[["1stFlrSF","2ndFlrSF","LowQualFinSF"]]
y = data[["BedroomAbvGr"]]


In [9]:
x

1stFlrSF  2ndFlrSF  LowQualFinSF
0          856       854             0
1         1262         0             0
2          920       866             0
3          961       756             0
4         1145      1053             0
...        ...       ...           ...
1455       953       694             0
1456      2073         0             0
1457      1188      1152             0
1458      1078         0             0
1459      1256         0             0

[1460 rows x 3 columns]

In [10]:
y

BedroomAbvGr
0                3
1                3
2                3
3                3
4                4
...            ...
1455             3
1456             3
1457             4
1458             2
1459             3

[1460 rows x 1 columns]

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [13]:
lr = LinearRegression()


In [14]:
fitting = lr.fit(x_train,y_train)
fitting

LinearRegression()

In [15]:
prediction = lr.predict(x_test)
prediction

array([[2.48619588],
       [3.80566131],
       [2.46692332],
       [3.10907848],
       [2.75215719],
       [2.27516135],
       [3.32866556],
       [2.97884971],
       [2.27516135],
       [2.90780192],
       [2.98845914],
       [2.39272396],
       [2.40236024],
       [2.711203  ],
       [3.1633165 ],
       [2.45728704],
       [3.24796723],
       [2.5179956 ],
       [2.45921429],
       [2.68422142],
       [2.84032915],
       [3.14667257],
       [3.05817363],
       [2.42259643],
       [2.66109435],
       [2.54931351],
       [2.61724928],
       [2.38790583],
       [3.08932569],
       [2.62303105],
       [2.73558902],
       [3.48642561],
       [4.25842807],
       [2.43030546],
       [2.75986622],
       [2.51895923],
       [3.27965008],
       [3.45042698],
       [3.77991505],
       [2.39657848],
       [2.76822149],
       [3.43994403],
       [2.42934183],
       [2.95548269],
       [2.44765076],
       [3.56137375],
       [2.4110329 ],
       [2.431

In [16]:
slope = lr.coef_
slope

array([[0.00048181, 0.00099048, 0.00112067]])

In [17]:
intercept = lr.intercept_
intercept

array([1.97161855])

In [18]:
mse=mean_squared_error (y_test , prediction)
mse

0.47898167804812136

In [19]:
x = data[["1stFlrSF","2ndFlrSF","LowQualFinSF"]]
y1 = data[["BsmtFullBath"]]

In [20]:
x_train,x_test,y_train,y_test = train_test_split(x,y1,test_size = 0.2,random_state = 42)

In [21]:
lr = LinearRegression()


In [22]:
fitting = lr.fit(x_train,y_train)
fitting

LinearRegression()

In [23]:
prediction = lr.predict(x_test)
prediction

array([[0.44775796],
       [0.41191566],
       [0.43643499],
       [0.33662336],
       [0.6040149 ],
       [0.32377147],
       [0.35214525],
       [0.30276054],
       [0.32377147],
       [0.3188477 ],
       [0.30912911],
       [0.39284157],
       [0.39850305],
       [0.5799536 ],
       [0.30921445],
       [0.43077351],
       [0.25919325],
       [0.46644086],
       [0.43190581],
       [0.56410144],
       [0.65581747],
       [0.25461839],
       [0.25033262],
       [0.41039217],
       [0.55051388],
       [0.48484068],
       [0.52475413],
       [0.39001083],
       [0.31200673],
       [0.52815102],
       [0.36585635],
       [0.28363378],
       [0.36438407],
       [0.41492136],
       [0.60854409],
       [0.467007  ],
       [0.35876805],
       [0.23284661],
       [0.36353762],
       [0.39510616],
       [0.29577197],
       [0.36620009],
       [0.41435521],
       [0.7234722 ],
       [0.42511203],
       [0.33345003],
       [0.40359839],
       [0.415

In [24]:
slope = lr.coef_
slope

array([[ 0.00028307, -0.00014094, -0.00022403]])

In [25]:
intercept = lr.intercept_
intercept

array([0.14543475])

In [26]:
mse=mean_squared_error (y_test , prediction)
mse

0.2386265620734243

In [27]:
x = data[["1stFlrSF","2ndFlrSF","LowQualFinSF"]]
y2 = data[["BsmtHalfBath"]]

In [28]:
x_train,x_test,y_train,y_test = train_test_split(x,y2,test_size = 0.2,random_state = 42)

In [29]:
fitting = lr.fit(x_train,y_train)
fitting

LinearRegression()

In [30]:
prediction = lr.predict(x_test)
prediction

array([[0.06582514],
       [0.03708637],
       [0.0663773 ],
       [0.05331126],
       [0.05820536],
       [0.07187126],
       [0.04828839],
       [0.05656568],
       [0.07187126],
       [0.05795494],
       [0.0562823 ],
       [0.0685031 ],
       [0.06822702],
       [0.0593787 ],
       [0.05241976],
       [0.06665337],
       [0.05110932],
       [0.06491408],
       [0.06659816],
       [0.06015172],
       [0.05567924],
       [0.05339746],
       [0.05539978],
       [0.06764726],
       [0.06081431],
       [0.06401682],
       [0.06207047],
       [0.06864114],
       [0.05402258],
       [0.06190482],
       [0.06123278],
       [0.04557003],
       [0.04578682],
       [0.06742639],
       [0.0579845 ],
       [0.06488647],
       [0.04929684],
       [0.0469326 ],
       [0.0381956 ],
       [0.06839267],
       [0.07494998],
       [0.04567383],
       [0.067454  ],
       [0.0523801 ],
       [0.06692945],
       [0.04335815],
       [0.06797855],
       [0.067

In [31]:
slope = lr.coef_
slope

array([[-1.38039395e-05, -2.02989913e-05,  1.56840183e-05]])

In [32]:
intercept = lr.intercept_
intercept

array([0.08056775])

In [33]:
mse=mean_squared_error (y_test , prediction)
mse

0.06199860273559237

In [34]:
x = data[["1stFlrSF","2ndFlrSF","LowQualFinSF"]]
y2 = data[["FullBath"]]

In [35]:
x_train,x_test,y_train,y_test = train_test_split(x,y2,test_size = 0.2,random_state = 42)

In [36]:
fitting = lr.fit(x_train,y_train)
fitting

LinearRegression()

In [37]:
prediction = lr.predict(x_test)
prediction

array([[1.2818677 ],
       [2.30465861],
       [1.25518809],
       [1.67132806],
       [1.65004629],
       [0.98972599],
       [1.86283653],
       [1.53331513],
       [0.98972599],
       [1.49227242],
       [1.54733414],
       [1.1524716 ],
       [1.1658114 ],
       [1.59335212],
       [1.68766769],
       [1.24184829],
       [1.70599091],
       [1.32588905],
       [1.24451625],
       [1.55600067],
       [1.77210549],
       [1.62021097],
       [1.54498067],
       [1.19382499],
       [1.52398514],
       [1.36924341],
       [1.46328903],
       [1.1458017 ],
       [1.63108867],
       [1.47129291],
       [1.40073209],
       [1.92147437],
       [2.03379518],
       [1.20449684],
       [1.66071813],
       [1.32722303],
       [1.83008585],
       [1.84226847],
       [2.23606345],
       [1.15780752],
       [0.91634689],
       [1.96601932],
       [1.20316286],
       [1.93151615],
       [1.22850848],
       [2.03095853],
       [1.17781723],
       [1.206

In [38]:
slope = lr.coef_
slope

array([[ 0.00066699,  0.00065477, -0.00054844]])

In [39]:
intercept = lr.intercept_
intercept

array([0.56952217])

In [40]:
mse=mean_squared_error (y_test , prediction)
mse

0.1780522791606842

In [41]:
x = data[["1stFlrSF","2ndFlrSF","LowQualFinSF"]]
y3 = data[["HalfBath"]]

In [42]:
x_train,x_test,y_train,y_test = train_test_split(x,y3,test_size = 0.2,random_state = 42)

In [43]:
fitting = lr.fit(x_train,y_train)
fitting

LinearRegression()

In [44]:
prediction = lr.predict(x_test)
prediction

array([[ 0.14357852],
       [ 0.9127548 ],
       [ 0.1433432 ],
       [ 0.59416364],
       [ 0.14682599],
       [ 0.14100173],
       [ 0.7022203 ],
       [ 0.55297382],
       [ 0.14100173],
       [ 0.49841182],
       [ 0.55241998],
       [ 0.1424372 ],
       [ 0.14255487],
       [ 0.14632593],
       [ 0.64986275],
       [ 0.14322554],
       [ 0.74351936],
       [ 0.14396681],
       [ 0.14324907],
       [ 0.14599647],
       [ 0.14790259],
       [ 0.69127276],
       [ 0.6458942 ],
       [ 0.14280196],
       [ 0.14571409],
       [ 0.14434921],
       [ 0.14517872],
       [ 0.14237837],
       [ 0.60600371],
       [ 0.14524932],
       [ 0.35871692],
       [ 0.85381999],
       [ 0.55152416],
       [ 0.14289608],
       [ 0.14692012],
       [ 0.14397857],
       [ 0.66873393],
       [ 0.88089886],
       [ 0.94331476],
       [ 0.14248427],
       [-0.05245146],
       [ 0.7512329 ],
       [ 0.14288432],
       [ 0.14930865],
       [ 0.14310788],
       [ 0

In [45]:
slope = lr.coef_
slope

array([[ 5.88309062e-06,  6.83275205e-04, -5.40409562e-04]])

In [46]:
intercept = lr.intercept_
intercept

array([0.13729538])

In [47]:
mse=mean_squared_error (y_test , prediction)
mse

0.14790983499439125

In [48]:
print("The prices of houses based on their square footage and the Basement Half Bathroom provided low Mean Square Error compare to other hence it is the best fitted LinearRegression Model")

The prices of houses based on their square footage and the Basement Half Bathroom provided low Mean Square Error compare to other hence it is the best fitted LinearRegression Model
